<a href="https://colab.research.google.com/github/mdaugherity/MachineLearning2023/blob/main/Class_1_23_2023_Intro_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#PHYS 453, Spring 2023, Dr. Daugherity
A quick intro to Python to review for this year

Examples of Markdown for text boxes are:
https://www.markdownguide.org/cheat-sheet/

Topics
* Loops
* Logic
* NUMPY 
* Plots

Don't forget we can also do equations with
$\LaTeX$
Examples:  $x=2$

$\frac{x}{2} = x^{234} + y_{12} \int \sin x dx - \alpha \Sigma$







Please set up sections like this:
# Title
## Header
### Subheader


# Basics

In [ ]:
# Code get comments
x = [1, 3.1415, 'steve']
print(x)


[1, 3.1415, 'steve']


In [ ]:
x

[1, 3.1415, 'steve']

In [ ]:
print("We can \t add \t\t tabs")
print("We can \n add \n\n new lines")

We can 	 add 		 tabs
We can 
 add 

 new lines


In [ ]:
x = 12
y = 3.141523452345
print(x,y)
print('The numbers are',x,y)

# Use f-strings to FORMAT strings
print(f"The numbers are x={x} and y={y}")
print(f"The numbers are x={x} and y={y:8.3f}")
print(f"The numbers are x={x} and y={y:8.3e}")


12 3.141523452345
The numbers are 12 3.141523452345
The numbers are x=12 and y=3.141523452345
The numbers are x=12 and y=   3.142
The numbers are x=12 and y=3.142e+00
We can 	 add 		 tabs
We can 
 add 

 new lines


In [ ]:
# Example of columns
print(f"{1}{2}{3}")
print(f"{1:8}{132:8}{3:8}")

123
       1     132       3


# LOOPS
IMPORTANT: Loops only work on **lists**


In [ ]:
for i in [0, 23.5, 'steve', 4]:
  print(i)

0
23.5
steve
4


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
i=0
while i<3:
  print(i)
  i+=1

0
1
2


# LOGIC

In [ ]:
i=0
if i==0:
  print('i is zero')

i is zero


In [ ]:
# NEVER test equality of floating-point numbers!
# INSTEAD check for being close enough
i=6/12
if abs(i-0.5) < 1e-6:
  print('i is close enough to one half')

i is close enough to one half


In [ ]:
x=2
y=3
if x==2 and y==3:
  print('x is 2 and y is 3')

x is 2 and y is 3


# NUMPY
Check out the user guide: https://numpy.org/doc/stable/user/index.html


In [ ]:
x = np.array([1,2,4])
print(x)

[1 2 4]


In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2,10,3)

array([2, 5, 8])

In [ ]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])